- https://claude.ai/chat/17520c22-dab4-4327-a86b-fa959f99e7d1

In [1]:
import torch
import torch.nn.functional as F

# Set random seed for reproducibility
torch.manual_seed(0)

# Create a 3x10 random matrix
x = torch.rand(3, 10)

print("Original matrix:")
print(x)
print()

# Method 1: Original implementation
def variance_method1(x):
    mean = x.mean(dim=-1, keepdim=True)
    mean_x2 = torch.square(x).mean(dim=-1, keepdim=True)
    var = mean_x2 - torch.square(mean)
    return var

# Method 2: Using torch.var()
def variance_method2(x):
    return torch.var(x, dim=-1, keepdim=True, unbiased=False)

# Calculate variances
var1 = variance_method1(x)
var2 = variance_method2(x)

print("Variance using Method 1 (original implementation):")
print(var1)
print()

print("Variance using Method 2 (torch.var()):")
print(var2)
print()

# Compare the results
diff = torch.abs(var1 - var2)
print("Absolute difference between methods:")
print(diff)
print()

print(f"Maximum difference: {diff.max().item()}")
print(f"Are results equal within 1e-6 tolerance? {torch.allclose(var1, var2, atol=1e-6)}")

Original matrix:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901, 0.8964, 0.4556,
         0.6323],
        [0.3489, 0.4017, 0.0223, 0.1689, 0.2939, 0.5185, 0.6977, 0.8000, 0.1610,
         0.2823],
        [0.6816, 0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362, 0.1852,
         0.3734]])

Variance using Method 1 (original implementation):
tensor([[0.0608],
        [0.0534],
        [0.0885]])

Variance using Method 2 (torch.var()):
tensor([[0.0608],
        [0.0534],
        [0.0885]])

Absolute difference between methods:
tensor([[3.7253e-08],
        [1.1176e-08],
        [2.2352e-08]])

Maximum difference: 3.725290298461914e-08
Are results equal within 1e-6 tolerance? True
